spring:
  application:
    name: bobb-gateway
  zipkin:
    base-url: http://localhost:8900
  http:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
server:
  port: 8080
  undertow:
    max-http-post-size: 0
    io-threads: 1
    worker-threads: 8
    buffer-size: 1024
    direct-buffers: true
eureka:
  instance:
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://172.31.47.243:8080/eureka/
###actuator监控点 start####
#endpoints:
#  health:
#    sensitive: false
#    enabled: true
##默认情况下很多端点是不允许访问的，会返回401:Unauthorized
#management:
#  security:
#    enabled: false
###actuator监控点 end####

###如下Oauth2.0配置参考##
###https://stackoverflow.com/questions/30327269/spring-oauth-authorization-server-behind-spring-cloud-zuul-proxy##
###https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/master/oauth2-vanilla/README.adoc##
###http://wiselyman.iteye.com/blog/2379419##
#######
zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 60000
  routes:
    bobb-oauth:
      path: /uaa/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: bobb-oauth
    bobb-owner:
      path: /owner/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: bobb-owner
    bobb-upms:
      path: /mss/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: bobb-upms
    bobb-member:
      path: /member/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: bobb-member
    bobb-hotel:
      path: /travel/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: bobb-hotel
    bobb-im:
      path: /im/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: bobb-im
    bobb-oa:
      path: /oa/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: bobb-oa
    kanran-booking:
      path: /booking/**
      strip-prefix: true
      serviceId: booking
  servlet-path: /
security:
  basic:
    enabled: false
  oauth2:
    #    sso:
    #      loginPath: /login
    #    client:
    #      ##网关的地址
    #      access-token-uri: http://localhost:9030/uaa/oauth/token
    #      user-authorization-uri: http://localhost:9030/uaa/oauth/authorize
    #      client-id: webApp
    #      client-secret: webApp
    resource:
      user-info-uri: http://172.31.2.92:7777/user
      prefer-token-info: false
#security:
#  oauth2:
#    resource:
#      id: gateway
#      user-info-uri: http://localhost:9060/user
#      prefer-token-info: false
##############end#####################
####超时配置####
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
###超时配置###
oauth2:
  white:
    list: /mss/code/**,/mss/smsCode/**,/mss/emailCode/**,/mss/inquiry/**,/mss/validated/**,/member/wxpay/**,/member/lector/**,/member/meeting/**,/member/user/**,/member/admin/enum/**,/member/change/phone/offline/**,/travel/ics/**,/travel/hotel/**,/travel/wxpay/**,/im/conversation/**,/im/message/**,/member/login/version,/owner/autonomous/**,/member/email/offline/**,/owner/region/find/region,/oa/chat/index,/booking/**,/oa/face/recognition/**

