spring:
  application:
    name: bobb-gateway
  zipkin:
    base-url: http://localhost:8900
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://172.31.36.103:8100/eureka/
###actuator监控点 start####
#endpoints:
#  health:
#    sensitive: false
#    enabled: true
##默认情况下很多端点是不允许访问的，会返回401:Unauthorized
#management:
#  security:
#    enabled: false
###actuator监控点 end####

###如下Oauth2.0配置参考##
###https://stackoverflow.com/questions/30327269/spring-oauth-authorization-server-behind-spring-cloud-zuul-proxy##
###https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/master/oauth2-vanilla/README.adoc##
###http://wiselyman.iteye.com/blog/2379419##
#######
zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 60000
  routes:
    bobb-oauth:
      path: /uaa/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: bobb-oauth
    bobb-owner:
      path: /owner/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: bobb-owner
    bobb-upms:
      path: /mss/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: bobb-upms
    bobb-member:
      path: /member/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: bobb-member
    bobb-hotel:
      path: /hotel/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: bobb-hotel
  #servlet-path: /
security:
  basic:
    enabled: false
  oauth2:
    #    sso:
    #      loginPath: /login
    #    client:
    #      ##网关的地址
    #      access-token-uri: http://localhost:9030/uaa/oauth/token
    #      user-authorization-uri: http://localhost:9030/uaa/oauth/authorize
    #      client-id: webApp
    #      client-secret: webApp
    resource:
      user-info-uri: http://localhost:8000/user
      prefer-token-info: false
#security:
#  oauth2:
#    resource:
#      id: gateway
#      user-info-uri: http://localhost:9060/user
#      prefer-token-info: false
##############end#####################
####超时配置####
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 120000
###超时配置###
###白名单配置###
oauth2:
  white:
    list: /**/v2/api-docs,/swagger-resources,/swagger-resources/**,/swagger-ui.html,/swagger-resources/configuration/ui,/configuration/ui,/configuration/security,/course/coursebase/**,/doc.html,/webjars/**,/mss/code/**,/mss/smsCode/**,/mss/emailCode/**,/mss/inquiry/**,/member/change/phone/offline/**,/member/register/apply
