spring:
  rabbitmq:
    host: 3.113.27.151
    username: canal
    port: 5672
    password: canal
    virtual-host: canal
    publisher-confirms: true
    cache:
      connection:
        mode: channel