server:
  port: 8080
spring:
  application:
    name: monitor
  boot:
    admin:
      ui:
        title: monitor
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://172.31.36.103:8100/eureka/